from yoyo import step

# Define the upgrade step
step(
    '''
    CREATE TABLE IF NOT EXISTS postmaster (did    integer PRIMARY KEY GENERATED BY DEFAULT AS identity,
    date DATE NOT NULL,title   varchar(100) NOT NULL CHECK (title <> ''),
    author   varchar(40) NOT NULL CHECK (author <> ''));
    '''
)

step(
    '''
   CREATE TABLE IF NOT EXISTS folders (id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   folder   varchar(40) NOT NULL CHECK (folder <> ''),
   did INT NOT NULL,CONSTRAINT fk_did FOREIGN KEY(did) 
   REFERENCES postmaster(did) ON DELETE CASCADE);
    '''
)

step(
    '''
   CREATE TABLE IF NOT EXISTS posttypes (id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   type   varchar(40) NOT NULL CHECK (type <> ''),
   did INT NOT NULL,CONSTRAINT fk_did FOREIGN KEY(did) 
   REFERENCES postmaster(did) ON DELETE CASCADE);
    '''
)
